sonar.projectKey=BX37-pipelineFinal-Backend
sonar.projectName=BX37-pipelineFinal-Backend
sonar.projectVersion=1.0

# Sources JS à la racine et dans routes/
sonar.sources=routes,server.js,models.js,db.js
sonar.tests=__tests__

# Fichiers de tests
sonar.test.inclusions=**/*.test.js

# Exclusions
sonar.exclusions=node_modules/**,coverage/**

# Rapport de couverture généré par Jest
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Pas de TypeScript ici
# sonar.typescript.tsconfigPath=tsconfig.json